---
title: "Chungil Chae (Chad)'s Research / Publication Portforlio"
subtitle: "2025, Spring"
author:
  - name: Chad (Chungil Chae)
    email: cchae@kean.edu
date: today
date-format: "ddd, D MMMM YYYY"
bibliography: _resource/reference.bib
csl: _resource/apa.csl
format: 
  html:
    theme: simplex
    toc: true
    toc_float: TRUE
    toc-depth: 4
    toc-location: left
    toc-title: TOPICS
    toc-font-size: .5em
    title-block-banner: true
    fig-cap-locatio: bottom
    tbl-cap-location: top
    fig-align: left
    reference-location: section
    footnotes-hover: true
    link-external-icon: true
    lightbox: true
    embed-resources: true
    code-tools: false
    code-fold: false
    highlight-style: dracula
    code-line-numbers: true
    code-overflow: scroll
  docx: 
    geometry: 
      - top=30mm
      - left=20mm
  pdf: 
    geometry: 
      - top=30mm
      - left=20mm
    header-includes:
      - \usepackage{kotex}
      - \usepackage{marginnote}
      - \usepackage{lineno}
      - \linenumbers
      - \usepackage{fancyhdr}
      - \usepackage{lipsum}
      - \pagestyle{fancy}
      - \fancyhead[HL]{Report}
      - \fancyfoot[CO,CE]{Copyright @ Chad (Chungil) Chae, since 2023}
      - \fancyfoot[LE,RO]{\thepage}
      - \usepackage{eso-pic,graphicx,transparent}
      - \usepackage{pdflscape}
      - \usepackage{fontspec}
      - \setmainfont[Mapping=tex-text]{Times New Roman}
      - \setsansfont[Mapping=tex-text]{Tahoma}
      - \newcommand{\blandscape}{\begin{landscape}}
      - \newcommand{\elandscape}{\end{landscape}}
#number-sections: true
#number-depth: 4
#mainfont: Georgia, serif;
#editor: visual
fontsize: .88em
abstract-title: "Abstract"
abstract: ""
---



```{r setup, echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE}
#knitr::opts_knit$set(root.dir= normalizePath('..'), echo = F)
knitr::opts_chunk$set(error = F, echo = F, warning = F, fig.width=8, fig.height=6)

```

# Research Statement
In the human resource development (HRD) field, analytics is increasingly central to understanding and improving organizational practices. My research, from my role as an Assistant Professor in Business Analytics at Wenzhou-Kean University, integrates analytics with HRD. This journey draws from diverse experiences spanning academic, technical, and practical realms.

My research history is extensive, encompassing a broad spectrum of subjects. However, it fundamentally centers on investigating the seamless integration of analytics into human behavior and HRD practices within organizations. These organizations face diverse learning and performance challenges, not only from traditional organizational issues but also from the advent of generative AI models like Large Language Models (LLMs) and emerging personnel issues in the post-COVID-19 era, such as remote work, virtual teams, and digital transformation. My work includes data mining, predictive analytics, and advanced statistical methods to gain deeper insights into organizational behavior, learning outcomes, and organizational development strategies.

I have extensively explored organizational behavior and management, focusing on knowledge sharing. This reflects a deep interest in understanding workplace culture, leadership, team dynamics, and employee performance. In my study “Building Social Capital and Learning Relationships through Knowledge Sharing: A Social Network Approach of Management Students’ Cases,” I investigated how socially constructed relationships within an organization affect its effectiveness, particularly regarding knowledge-sharing behaviors. Another study, “Organizational Support on Knowledge Sharing: A Moderated Mediation Model of Job Characteristics and Orgaizational Citizenship Behavior,” revealed that an employee's intention to share knowledge is influenced by their perception of organizational support, their voluntary behavior to exceed job, and the nature of their job. For instance, jobs offering more autonomy or requiring various skills might encourage more knowledge sharing. During COVID-19, retaining talent in multinational corporations was a critical issue. This led me to explore factors contributing to employee retention in my study, “Career Growth Opportunity on Turnover Intention: The Mediating Role of Organizational Commitment in Multinational Corporations.” I learned about the crucial role of career growth opportunities in retaining local talent.

A significant part of my work involves a deep dive into the synergies between industry advancements and technological innovations and the exploration of educational and learning technologies. My research aims to bridge the gap between technology, educational methodologies, and industry practices. It offers insights into how digital tools and content can enhance learning experiences and contribute to sustainable economic development. Focusing on educational and learning technologies, my research enhances and understands the impact of various tools and methods in tutoring and online learning systems. This exploration is informed by a comprehensive list of over 140 tools used in tutoring systems, ranging from complete systems to specialized tools for preparing instructional materials. Central to my research is recognizing the diverse needs of learners and stakeholders in education technology. This diversity requires a variety of tutoring architectures and supplementary tools, as no single system can effectively cater to all use cases. My research extends into informal learning, particularly in virtual practice communities. It examines how emergent learning platforms, equipped with new technologies and digital content, can foster learner-driven professional development. Another vital aspect of my research involves examining learner engagement in Massive Open Online Courses (MOOCs). Using binomial logistic regression models and qualitative content analysis, I have investigated how different forms of student engagement, such as interaction with videos and forum posts, influence their overall achievement in MOOCs. This research has revealed that students' active participation and intention to receive certification significantly impact their probability of course completion. In addition to educational pursuits, my research in industry and technology studies include studying powder metallurgy parts manufacturing in North-Central Pennsylvania. This study focuses on the industry's adaptation to changing technological and market demands. Furthermore, I have explored the dynamics of investor activity in Chinese financial institutions, analyzing how market information acquisition influences individual and institutional investment behaviors.

Human Resource Development (HRD) is my key domain research area. I explore various topics within this field, including development, learning, and performance. My significant contribution to HRD research involves applying advanced methodologies like bibliometrics, social network analysis (specifically ERGM models on research collaboration), and computational topic modeling (such as LDA and STM). These techniques help map the evolving nature of HRD and forecast its future directions. I aim to provide valuable insights for scholars, practitioners, and students in HRD, aiding their decision-making and inspiring innovative research. One of my studies, “Conceptual Organization and Identity of HRD,” examines the historical development of HRD, its evolving definitions, competition among major paradigms, and the diversification of research topics. This study is crucial for understanding the fundamental changes that have shaped HRD. Another research piece, “Bibliometric Keywords Network Analysis of Human Resource Management Research Trends in South Korea,” takes a closer look at HRM research within the Korean context. It uncovers complex semantic networks and themes, showing how global HRM trends are adapted in South Korea. In “Research Topics and Collaboration in Human Resource Development Review,” I delve into the HRDR journal's research trends using computational methods. This reveals an expansion of HRD research topics, including diversity, critical HRD, and equity issues. Similarly, “Research Topics and Intellectual Structure in Human Resource Development International” provides insights into the HRDI journal, particularly the changes during the COVID-19 pandemic, focusing on international and cross-cultural HRD research. Lastly, from my recent study, “People Analytics and Human Resource Development–Research Landscape and Future Needs,” I want to provide a new direction to HRD by focusing on the role of technology and analytics in HRD. It looks at current and future trends in People Analytics within HRD, focusing on workforce planning, data-informed decision-making, and the ethical aspects of data analytics in HR.

Additionally, my work transcends traditional academic boundaries, embracing a cross-disciplinary approach integrating insights from various fields to provide a more holistic understanding of these complex subjects. My cross-disciplinary study and diversity and cultural issues aim to expand my research area. My research endeavors are grounded in a cross-disciplinary approach, recognizing academic inquiries' intricate and multifaceted nature. This approach is evident in the study of a 'transdiagnostic' perspective in psychiatry, which challenges traditional psychiatric classifications and seeks to understand mental disorders beyond conventional diagnoses. Furthermore, my research extends to exploring persistent issues of gender inequality in academic medicine, as discussed in “Looking into the Labyrinth of Gender Inequality: Women Physicians in Academic Medicine". This work underscores the cultural and social dynamics that perpetuate gender disparities, particularly in the context of South Korean women physicians. By examining the cultural practices and implicit biases that influence career trajectories in academic medicine, my research seeks to contribute to a deeper understanding of gender inequality and its pervasive effects in various professional fields. Additionally, my investigation into the psychological capital of international students demonstrates my interest in the interplay between psychology and cultural adjustment in educational settings. This research highlights the significance of positive psychological attributes and their impact on students' engagement and organizational behaviors, further emphasizing the importance of cultural considerations in academic and social environments. My work aims to expand the research area through these studies by integrating diverse perspectives and insights from various disciplines. This cross-disciplinary approach enriches the academic discourse and offers a more holistic and culturally sensitive understanding of complex subjects such as mental health, gender inequality, and cultural adaptation in educational contexts.

This broad spectrum of my research interests and history highlights my commitment to examining the multifaceted nature of human resource development within the evolving landscape of modern industries. My previous research history, experience, and knowledge guide my future research. I am particularly interested in developing insights into how digital tools can enhance learning experiences and contribute to sustainable development. Another key focus will be on the role of analytics in workforce planning and the ethical considerations in data utilization within HRD. Along with advanced research methods and domain knowledge, I pursue the advancement of research for transforming traditional HRD strategies using data-driven approaches, enhancing their effectiveness and adaptability in contemporary workplaces with new paradigms such as digital transformation and applying people/HR analytics in organizations. Additionally, my research will continue to integrate cross-disciplinary insights to address complex challenges in HRD, including cultural and gender dynamics in professional settings.
